language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

env:
    - LIBRE=re LIBREM=rem

sudo: require

addons:
    apt:
        packages:
            libssl-dev

install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install mingw32 wine; else brew install i386-mingw32-gcc wine; fi
    - git clone https://github.com/creytiv/re.git
    - git clone https://github.com/creytiv/rem.git
    - git clone https://github.com/creytiv/retest.git
    - git clone https://github.com/creytiv/baresip.git
    - curl -OL 'https://github.com/alfredh/pytools/raw/master/ccheck.py'
    - for p in ${LIBRE} ${LIBREM}; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script:
    ###- make openssl V=1 CCACHE= 
    - make V=1 CCACHE= 
    - make V=1 CCACHE= EXTRA_CFLAGS=-Werror info test modules
    - python2 ccheck.py
