language: c

# Test with mingw 32 bit
    - os: linux
      compiler: x86_64-w64-mingw32-g++
      env: OPJ_CI_CC=x86_64-w64-mingw32-gcc OPJ_CI_CXX=x86_64-w64-mingw32-g++ OPJ_CI_ARCH=i386 OPJ_CI_BUILD_CONFIGURATION=Release
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - gcc-mingw-w64      
            - g++-mingw-w64-i686
            - gcc-multilib
            - g++-multilib

# Test with mingw 64 bit
    - os: linux
      compiler: x86_64-w64-mingw32-g++
      env: OPJ_CI_CC=x86_64-w64-mingw32-gcc OPJ_CI_CXX=x86_64-w64-mingw32-g++ OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Release
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64
            - g++-mingw-w64-x86-64


os:
    - linux
    - osx

compiler:
    - clang
    - gcc

env:
    - LIBRE=re LIBREM=rem

sudo: require

addons:
    apt:
        packages:
            libssl-dev
            mingw-w64
            wine

before_install:
###- brew install i386-mingw32-gcc wine
####- brew cask uninstall oclint
- if [ $TRAVIS_OS_NAME = osx ]; then brew install mingw-w64 wine; else echo "IF-FOO-DUMMY"; fi

install:
    ###- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install mingw32 wine; else brew install i386-mingw32-gcc wine; fi
    - git clone http://github.com/creytiv/re.git
    - git clone http://github.com/creytiv/rem.git
    - git clone http://github.com/creytiv/retest.git
    - git clone http://github.com/alfredh/baresip.git
    - curl -OL 'https://github.com/alfredh/pytools/raw/master/ccheck.py'
    - for p in ${LIBRE} ${LIBREM}; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script:
    ###- make openssl V=1 CCACHE= 
    - make V=1 CCACHE= TUPLE=i686-w64-mingw32
###- make V=1 CCACHE= 
    - make V=1 CCACHE= TUPLE=i686-w64-mingw32 EXTRA_CFLAGS=-Werror info test modules
    - python2 ccheck.py



